package com.deutscheboerse.risk.dave.model;

public enum ModelType {
    ACCOUNT_MARGIN_MODEL,
    LIQUI_GROUP_MARGIN_MODEL,
    LIQUI_GROUP_SPLIT_MARGIN_MODEL,
    POOL_MARGIN_MODEL,
    POSITION_REPORT_MODEL,
    RISK_LIMIT_UTILIZATION_MODEL
}
